// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUpstreamGroupUpdate is the builder for updating AccountUpstreamGroup entities.
type AccountUpstreamGroupUpdate struct {
	config
	hooks    []Hook
	mutation *AccountUpstreamGroupMutation
}

// Where appends a list predicates to the AccountUpstreamGroupUpdate builder.
func (_u *AccountUpstreamGroupUpdate) Where(ps ...predicate.AccountUpstreamGroup) *AccountUpstreamGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamGroupUpdate) SetUpdatedAt(v time.Time) *AccountUpstreamGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpstreamGroupUpdate) SetName(v string) *AccountUpstreamGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdate) SetNillableName(v *string) *AccountUpstreamGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountUpstreamGroupUpdate) SetNormalizedName(v string) *AccountUpstreamGroupUpdate {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdate) SetNillableNormalizedName(v *string) *AccountUpstreamGroupUpdate {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountUpstreamGroupUpdate) SetSortOrder(v int64) *AccountUpstreamGroupUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdate) SetNillableSortOrder(v *int64) *AccountUpstreamGroupUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountUpstreamGroupUpdate) AddSortOrder(v int64) *AccountUpstreamGroupUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountUpstreamGroupUpdate) AddAccountIDs(ids ...int64) *AccountUpstreamGroupUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountUpstreamGroupUpdate) AddAccounts(v ...*Account) *AccountUpstreamGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountUpstreamGroupMutation object of the builder.
func (_u *AccountUpstreamGroupUpdate) Mutation() *AccountUpstreamGroupMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountUpstreamGroupUpdate) ClearAccounts() *AccountUpstreamGroupUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountUpstreamGroupUpdate) RemoveAccountIDs(ids ...int64) *AccountUpstreamGroupUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountUpstreamGroupUpdate) RemoveAccounts(v ...*Account) *AccountUpstreamGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpstreamGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpstreamGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreamgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountupstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`enttmp: validator failed for field "AccountUpstreamGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accountupstreamgroup.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`enttmp: validator failed for field "AccountUpstreamGroup.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreamgroup.Table, accountupstreamgroup.Columns, sqlgraph.NewFieldSpec(accountupstreamgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreamgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountupstreamgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accountupstreamgroup.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accountupstreamgroup.FieldSortOrder, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accountupstreamgroup.FieldSortOrder, field.TypeInt64, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpstreamGroupUpdateOne is the builder for updating a single AccountUpstreamGroup entity.
type AccountUpstreamGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountUpstreamGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamGroupUpdateOne) SetUpdatedAt(v time.Time) *AccountUpstreamGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpstreamGroupUpdateOne) SetName(v string) *AccountUpstreamGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdateOne) SetNillableName(v *string) *AccountUpstreamGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNormalizedName sets the "normalized_name" field.
func (_u *AccountUpstreamGroupUpdateOne) SetNormalizedName(v string) *AccountUpstreamGroupUpdateOne {
	_u.mutation.SetNormalizedName(v)
	return _u
}

// SetNillableNormalizedName sets the "normalized_name" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdateOne) SetNillableNormalizedName(v *string) *AccountUpstreamGroupUpdateOne {
	if v != nil {
		_u.SetNormalizedName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AccountUpstreamGroupUpdateOne) SetSortOrder(v int64) *AccountUpstreamGroupUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AccountUpstreamGroupUpdateOne) SetNillableSortOrder(v *int64) *AccountUpstreamGroupUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AccountUpstreamGroupUpdateOne) AddSortOrder(v int64) *AccountUpstreamGroupUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *AccountUpstreamGroupUpdateOne) AddAccountIDs(ids ...int64) *AccountUpstreamGroupUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *AccountUpstreamGroupUpdateOne) AddAccounts(v ...*Account) *AccountUpstreamGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the AccountUpstreamGroupMutation object of the builder.
func (_u *AccountUpstreamGroupUpdateOne) Mutation() *AccountUpstreamGroupMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *AccountUpstreamGroupUpdateOne) ClearAccounts() *AccountUpstreamGroupUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *AccountUpstreamGroupUpdateOne) RemoveAccountIDs(ids ...int64) *AccountUpstreamGroupUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *AccountUpstreamGroupUpdateOne) RemoveAccounts(v ...*Account) *AccountUpstreamGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the AccountUpstreamGroupUpdate builder.
func (_u *AccountUpstreamGroupUpdateOne) Where(ps ...predicate.AccountUpstreamGroup) *AccountUpstreamGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpstreamGroupUpdateOne) Select(field string, fields ...string) *AccountUpstreamGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountUpstreamGroup entity.
func (_u *AccountUpstreamGroupUpdateOne) Save(ctx context.Context) (*AccountUpstreamGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamGroupUpdateOne) SaveX(ctx context.Context) *AccountUpstreamGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpstreamGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreamgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountupstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`enttmp: validator failed for field "AccountUpstreamGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedName(); ok {
		if err := accountupstreamgroup.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`enttmp: validator failed for field "AccountUpstreamGroup.normalized_name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamGroupUpdateOne) sqlSave(ctx context.Context) (_node *AccountUpstreamGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreamgroup.Table, accountupstreamgroup.Columns, sqlgraph.NewFieldSpec(accountupstreamgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`enttmp: missing "AccountUpstreamGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountupstreamgroup.FieldID)
		for _, f := range fields {
			if !accountupstreamgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("enttmp: invalid field %q for query", f)}
			}
			if f != accountupstreamgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreamgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountupstreamgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedName(); ok {
		_spec.SetField(accountupstreamgroup.FieldNormalizedName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(accountupstreamgroup.FieldSortOrder, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(accountupstreamgroup.FieldSortOrder, field.TypeInt64, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountUpstreamGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
