// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUpstreamGroupDelete is the builder for deleting a AccountUpstreamGroup entity.
type AccountUpstreamGroupDelete struct {
	config
	hooks    []Hook
	mutation *AccountUpstreamGroupMutation
}

// Where appends a list predicates to the AccountUpstreamGroupDelete builder.
func (_d *AccountUpstreamGroupDelete) Where(ps ...predicate.AccountUpstreamGroup) *AccountUpstreamGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountUpstreamGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUpstreamGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountUpstreamGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountupstreamgroup.Table, sqlgraph.NewFieldSpec(accountupstreamgroup.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountUpstreamGroupDeleteOne is the builder for deleting a single AccountUpstreamGroup entity.
type AccountUpstreamGroupDeleteOne struct {
	_d *AccountUpstreamGroupDelete
}

// Where appends a list predicates to the AccountUpstreamGroupDelete builder.
func (_d *AccountUpstreamGroupDeleteOne) Where(ps ...predicate.AccountUpstreamGroup) *AccountUpstreamGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountUpstreamGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountupstreamgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUpstreamGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
