// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreamgroup"
)

// AccountUpstreamGroupCreate is the builder for creating a AccountUpstreamGroup entity.
type AccountUpstreamGroupCreate struct {
	config
	mutation *AccountUpstreamGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountUpstreamGroupCreate) SetCreatedAt(v time.Time) *AccountUpstreamGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountUpstreamGroupCreate) SetNillableCreatedAt(v *time.Time) *AccountUpstreamGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountUpstreamGroupCreate) SetUpdatedAt(v time.Time) *AccountUpstreamGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountUpstreamGroupCreate) SetNillableUpdatedAt(v *time.Time) *AccountUpstreamGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountUpstreamGroupCreate) SetName(v string) *AccountUpstreamGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNormalizedName sets the "normalized_name" field.
func (_c *AccountUpstreamGroupCreate) SetNormalizedName(v string) *AccountUpstreamGroupCreate {
	_c.mutation.SetNormalizedName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AccountUpstreamGroupCreate) SetSortOrder(v int64) *AccountUpstreamGroupCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AccountUpstreamGroupCreate) SetNillableSortOrder(v *int64) *AccountUpstreamGroupCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *AccountUpstreamGroupCreate) AddAccountIDs(ids ...int64) *AccountUpstreamGroupCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *AccountUpstreamGroupCreate) AddAccounts(v ...*Account) *AccountUpstreamGroupCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the AccountUpstreamGroupMutation object of the builder.
func (_c *AccountUpstreamGroupCreate) Mutation() *AccountUpstreamGroupMutation {
	return _c.mutation
}

// Save creates the AccountUpstreamGroup in the database.
func (_c *AccountUpstreamGroupCreate) Save(ctx context.Context) (*AccountUpstreamGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUpstreamGroupCreate) SaveX(ctx context.Context) *AccountUpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUpstreamGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountupstreamgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountupstreamgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := accountupstreamgroup.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUpstreamGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountUpstreamGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountUpstreamGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountUpstreamGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountupstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedName(); !ok {
		return &ValidationError{Name: "normalized_name", err: errors.New(`ent: missing required field "AccountUpstreamGroup.normalized_name"`)}
	}
	if v, ok := _c.mutation.NormalizedName(); ok {
		if err := accountupstreamgroup.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamGroup.normalized_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "AccountUpstreamGroup.sort_order"`)}
	}
	return nil
}

func (_c *AccountUpstreamGroupCreate) sqlSave(ctx context.Context) (*AccountUpstreamGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUpstreamGroupCreate) createSpec() (*AccountUpstreamGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUpstreamGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountupstreamgroup.Table, sqlgraph.NewFieldSpec(accountupstreamgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountupstreamgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreamgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountupstreamgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NormalizedName(); ok {
		_spec.SetField(accountupstreamgroup.FieldNormalizedName, field.TypeString, value)
		_node.NormalizedName = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(accountupstreamgroup.FieldSortOrder, field.TypeInt64, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountupstreamgroup.AccountsTable,
			Columns: []string{accountupstreamgroup.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamGroupCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamGroupUpsertOne {
	_c.conflict = opts
	return &AccountUpstreamGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamGroupCreate) OnConflictColumns(columns ...string) *AccountUpstreamGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamGroupUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpstreamGroupUpsertOne is the builder for "upsert"-ing
	//  one AccountUpstreamGroup node.
	AccountUpstreamGroupUpsertOne struct {
		create *AccountUpstreamGroupCreate
	}

	// AccountUpstreamGroupUpsert is the "OnConflict" setter.
	AccountUpstreamGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamGroupUpsert) SetUpdatedAt(v time.Time) *AccountUpstreamGroupUpsert {
	u.Set(accountupstreamgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsert) UpdateUpdatedAt() *AccountUpstreamGroupUpsert {
	u.SetExcluded(accountupstreamgroup.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountUpstreamGroupUpsert) SetName(v string) *AccountUpstreamGroupUpsert {
	u.Set(accountupstreamgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsert) UpdateName() *AccountUpstreamGroupUpsert {
	u.SetExcluded(accountupstreamgroup.FieldName)
	return u
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountUpstreamGroupUpsert) SetNormalizedName(v string) *AccountUpstreamGroupUpsert {
	u.Set(accountupstreamgroup.FieldNormalizedName, v)
	return u
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsert) UpdateNormalizedName() *AccountUpstreamGroupUpsert {
	u.SetExcluded(accountupstreamgroup.FieldNormalizedName)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountUpstreamGroupUpsert) SetSortOrder(v int64) *AccountUpstreamGroupUpsert {
	u.Set(accountupstreamgroup.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsert) UpdateSortOrder() *AccountUpstreamGroupUpsert {
	u.SetExcluded(accountupstreamgroup.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountUpstreamGroupUpsert) AddSortOrder(v int64) *AccountUpstreamGroupUpsert {
	u.Add(accountupstreamgroup.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamGroupUpsertOne) UpdateNewValues() *AccountUpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountupstreamgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpstreamGroupUpsertOne) Ignore() *AccountUpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamGroupUpsertOne) DoNothing() *AccountUpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamGroupCreate.OnConflict
// documentation for more info.
func (u *AccountUpstreamGroupUpsertOne) Update(set func(*AccountUpstreamGroupUpsert)) *AccountUpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamGroupUpsertOne) SetUpdatedAt(v time.Time) *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertOne) UpdateUpdatedAt() *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountUpstreamGroupUpsertOne) SetName(v string) *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertOne) UpdateName() *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountUpstreamGroupUpsertOne) SetNormalizedName(v string) *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertOne) UpdateNormalizedName() *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountUpstreamGroupUpsertOne) SetSortOrder(v int64) *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountUpstreamGroupUpsertOne) AddSortOrder(v int64) *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertOne) UpdateSortOrder() *AccountUpstreamGroupUpsertOne {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountUpstreamGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpstreamGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpstreamGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUpstreamGroupCreateBulk is the builder for creating many AccountUpstreamGroup entities in bulk.
type AccountUpstreamGroupCreateBulk struct {
	config
	err      error
	builders []*AccountUpstreamGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUpstreamGroup entities in the database.
func (_c *AccountUpstreamGroupCreateBulk) Save(ctx context.Context) ([]*AccountUpstreamGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUpstreamGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUpstreamGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUpstreamGroupCreateBulk) SaveX(ctx context.Context) []*AccountUpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamGroupUpsertBulk {
	_c.conflict = opts
	return &AccountUpstreamGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamGroupCreateBulk) OnConflictColumns(columns ...string) *AccountUpstreamGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamGroupUpsertBulk{
		create: _c,
	}
}

// AccountUpstreamGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUpstreamGroup nodes.
type AccountUpstreamGroupUpsertBulk struct {
	create *AccountUpstreamGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamGroupUpsertBulk) UpdateNewValues() *AccountUpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountupstreamgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpstreamGroupUpsertBulk) Ignore() *AccountUpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamGroupUpsertBulk) DoNothing() *AccountUpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamGroupCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpstreamGroupUpsertBulk) Update(set func(*AccountUpstreamGroupUpsert)) *AccountUpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamGroupUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertBulk) UpdateUpdatedAt() *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountUpstreamGroupUpsertBulk) SetName(v string) *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertBulk) UpdateName() *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetNormalizedName sets the "normalized_name" field.
func (u *AccountUpstreamGroupUpsertBulk) SetNormalizedName(v string) *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetNormalizedName(v)
	})
}

// UpdateNormalizedName sets the "normalized_name" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertBulk) UpdateNormalizedName() *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateNormalizedName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AccountUpstreamGroupUpsertBulk) SetSortOrder(v int64) *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AccountUpstreamGroupUpsertBulk) AddSortOrder(v int64) *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AccountUpstreamGroupUpsertBulk) UpdateSortOrder() *AccountUpstreamGroupUpsertBulk {
	return u.Update(func(s *AccountUpstreamGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *AccountUpstreamGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUpstreamGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
