// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreamgroup"
)

// AccountUpstreamGroup is the model entity for the AccountUpstreamGroup schema.
type AccountUpstreamGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NormalizedName holds the value of the "normalized_name" field.
	NormalizedName string `json:"normalized_name,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int64 `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountUpstreamGroupQuery when eager-loading is set.
	Edges        AccountUpstreamGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountUpstreamGroupEdges holds the relations/edges for other nodes in the graph.
type AccountUpstreamGroupEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e AccountUpstreamGroupEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountUpstreamGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountupstreamgroup.FieldID, accountupstreamgroup.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case accountupstreamgroup.FieldName, accountupstreamgroup.FieldNormalizedName:
			values[i] = new(sql.NullString)
		case accountupstreamgroup.FieldCreatedAt, accountupstreamgroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountUpstreamGroup fields.
func (_m *AccountUpstreamGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountupstreamgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountupstreamgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountupstreamgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountupstreamgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountupstreamgroup.FieldNormalizedName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_name", values[i])
			} else if value.Valid {
				_m.NormalizedName = value.String
			}
		case accountupstreamgroup.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountUpstreamGroup.
// This includes values selected through modifiers, order, etc.
func (_m *AccountUpstreamGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the AccountUpstreamGroup entity.
func (_m *AccountUpstreamGroup) QueryAccounts() *AccountQuery {
	return NewAccountUpstreamGroupClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this AccountUpstreamGroup.
// Note that you need to call AccountUpstreamGroup.Unwrap() before calling this method if this AccountUpstreamGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountUpstreamGroup) Update() *AccountUpstreamGroupUpdateOne {
	return NewAccountUpstreamGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountUpstreamGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountUpstreamGroup) Unwrap() *AccountUpstreamGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("enttmp: AccountUpstreamGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountUpstreamGroup) String() string {
	var builder strings.Builder
	builder.WriteString("AccountUpstreamGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("normalized_name=")
	builder.WriteString(_m.NormalizedName)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// AccountUpstreamGroups is a parsable slice of AccountUpstreamGroup.
type AccountUpstreamGroups []*AccountUpstreamGroup
