// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodebatchusage"
)

// RedeemCodeBatchUsageCreate is the builder for creating a RedeemCodeBatchUsage entity.
type RedeemCodeBatchUsageCreate struct {
	config
	mutation *RedeemCodeBatchUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *RedeemCodeBatchUsageCreate) SetBatchID(v string) *RedeemCodeBatchUsageCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RedeemCodeBatchUsageCreate) SetUserID(v int64) *RedeemCodeBatchUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCodeBatchUsageCreate) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *RedeemCodeBatchUsageCreate) SetUsedAt(v time.Time) *RedeemCodeBatchUsageCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *RedeemCodeBatchUsageCreate) SetNillableUsedAt(v *time.Time) *RedeemCodeBatchUsageCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemCodeBatchUsageMutation object of the builder.
func (_c *RedeemCodeBatchUsageCreate) Mutation() *RedeemCodeBatchUsageMutation {
	return _c.mutation
}

// Save creates the RedeemCodeBatchUsage in the database.
func (_c *RedeemCodeBatchUsageCreate) Save(ctx context.Context) (*RedeemCodeBatchUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCodeBatchUsageCreate) SaveX(ctx context.Context) *RedeemCodeBatchUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeBatchUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeBatchUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCodeBatchUsageCreate) defaults() {
	if _, ok := _c.mutation.UsedAt(); !ok {
		v := redeemcodebatchusage.DefaultUsedAt()
		_c.mutation.SetUsedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCodeBatchUsageCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "RedeemCodeBatchUsage.batch_id"`)}
	}
	if v, ok := _c.mutation.BatchID(); ok {
		if err := redeemcodebatchusage.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "RedeemCodeBatchUsage.batch_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RedeemCodeBatchUsage.user_id"`)}
	}
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemCodeBatchUsage.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		return &ValidationError{Name: "used_at", err: errors.New(`ent: missing required field "RedeemCodeBatchUsage.used_at"`)}
	}
	return nil
}

func (_c *RedeemCodeBatchUsageCreate) sqlSave(ctx context.Context) (*RedeemCodeBatchUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCodeBatchUsageCreate) createSpec() (*RedeemCodeBatchUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCodeBatchUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcodebatchusage.Table, sqlgraph.NewFieldSpec(redeemcodebatchusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldBatchID, field.TypeString, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeBatchUsage.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeBatchUsageUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeBatchUsageCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCodeBatchUsageUpsertOne {
	_c.conflict = opts
	return &RedeemCodeBatchUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeBatchUsageCreate) OnConflictColumns(columns ...string) *RedeemCodeBatchUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeBatchUsageUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCodeBatchUsageUpsertOne is the builder for "upsert"-ing
	//  one RedeemCodeBatchUsage node.
	RedeemCodeBatchUsageUpsertOne struct {
		create *RedeemCodeBatchUsageCreate
	}

	// RedeemCodeBatchUsageUpsert is the "OnConflict" setter.
	RedeemCodeBatchUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *RedeemCodeBatchUsageUpsert) SetBatchID(v string) *RedeemCodeBatchUsageUpsert {
	u.Set(redeemcodebatchusage.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsert) UpdateBatchID() *RedeemCodeBatchUsageUpsert {
	u.SetExcluded(redeemcodebatchusage.FieldBatchID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeBatchUsageUpsert) SetUserID(v int64) *RedeemCodeBatchUsageUpsert {
	u.Set(redeemcodebatchusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsert) UpdateUserID() *RedeemCodeBatchUsageUpsert {
	u.SetExcluded(redeemcodebatchusage.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCodeBatchUsageUpsert) AddUserID(v int64) *RedeemCodeBatchUsageUpsert {
	u.Add(redeemcodebatchusage.FieldUserID, v)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsert) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsert {
	u.Set(redeemcodebatchusage.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsert) UpdateRedeemCodeID() *RedeemCodeBatchUsageUpsert {
	u.SetExcluded(redeemcodebatchusage.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsert) AddRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsert {
	u.Add(redeemcodebatchusage.FieldRedeemCodeID, v)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *RedeemCodeBatchUsageUpsert) SetUsedAt(v time.Time) *RedeemCodeBatchUsageUpsert {
	u.Set(redeemcodebatchusage.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsert) UpdateUsedAt() *RedeemCodeBatchUsageUpsert {
	u.SetExcluded(redeemcodebatchusage.FieldUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeBatchUsageUpsertOne) UpdateNewValues() *RedeemCodeBatchUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCodeBatchUsageUpsertOne) Ignore() *RedeemCodeBatchUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeBatchUsageUpsertOne) DoNothing() *RedeemCodeBatchUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeBatchUsageCreate.OnConflict
// documentation for more info.
func (u *RedeemCodeBatchUsageUpsertOne) Update(set func(*RedeemCodeBatchUsageUpsert)) *RedeemCodeBatchUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeBatchUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *RedeemCodeBatchUsageUpsertOne) SetBatchID(v string) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertOne) UpdateBatchID() *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeBatchUsageUpsertOne) SetUserID(v int64) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCodeBatchUsageUpsertOne) AddUserID(v int64) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertOne) UpdateUserID() *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsertOne) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsertOne) AddRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertOne) UpdateRedeemCodeID() *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *RedeemCodeBatchUsageUpsertOne) SetUsedAt(v time.Time) *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertOne) UpdateUsedAt() *RedeemCodeBatchUsageUpsertOne {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateUsedAt()
	})
}

// Exec executes the query.
func (u *RedeemCodeBatchUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeBatchUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeBatchUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCodeBatchUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCodeBatchUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCodeBatchUsageCreateBulk is the builder for creating many RedeemCodeBatchUsage entities in bulk.
type RedeemCodeBatchUsageCreateBulk struct {
	config
	err      error
	builders []*RedeemCodeBatchUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCodeBatchUsage entities in the database.
func (_c *RedeemCodeBatchUsageCreateBulk) Save(ctx context.Context) ([]*RedeemCodeBatchUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCodeBatchUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCodeBatchUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCodeBatchUsageCreateBulk) SaveX(ctx context.Context) []*RedeemCodeBatchUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeBatchUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeBatchUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeBatchUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeBatchUsageUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeBatchUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCodeBatchUsageUpsertBulk {
	_c.conflict = opts
	return &RedeemCodeBatchUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeBatchUsageCreateBulk) OnConflictColumns(columns ...string) *RedeemCodeBatchUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeBatchUsageUpsertBulk{
		create: _c,
	}
}

// RedeemCodeBatchUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCodeBatchUsage nodes.
type RedeemCodeBatchUsageUpsertBulk struct {
	create *RedeemCodeBatchUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeBatchUsageUpsertBulk) UpdateNewValues() *RedeemCodeBatchUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeBatchUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCodeBatchUsageUpsertBulk) Ignore() *RedeemCodeBatchUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeBatchUsageUpsertBulk) DoNothing() *RedeemCodeBatchUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeBatchUsageCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCodeBatchUsageUpsertBulk) Update(set func(*RedeemCodeBatchUsageUpsert)) *RedeemCodeBatchUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeBatchUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *RedeemCodeBatchUsageUpsertBulk) SetBatchID(v string) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertBulk) UpdateBatchID() *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeBatchUsageUpsertBulk) SetUserID(v int64) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCodeBatchUsageUpsertBulk) AddUserID(v int64) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertBulk) UpdateUserID() *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsertBulk) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCodeBatchUsageUpsertBulk) AddRedeemCodeID(v int64) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertBulk) UpdateRedeemCodeID() *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *RedeemCodeBatchUsageUpsertBulk) SetUsedAt(v time.Time) *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *RedeemCodeBatchUsageUpsertBulk) UpdateUsedAt() *RedeemCodeBatchUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeBatchUsageUpsert) {
		s.UpdateUsedAt()
	})
}

// Exec executes the query.
func (u *RedeemCodeBatchUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCodeBatchUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeBatchUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeBatchUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
