// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodebatchusage"
)

// RedeemCodeBatchUsageUpdate is the builder for updating RedeemCodeBatchUsage entities.
type RedeemCodeBatchUsageUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCodeBatchUsageMutation
}

// Where appends a list predicates to the RedeemCodeBatchUsageUpdate builder.
func (_u *RedeemCodeBatchUsageUpdate) Where(ps ...predicate.RedeemCodeBatchUsage) *RedeemCodeBatchUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *RedeemCodeBatchUsageUpdate) SetBatchID(v string) *RedeemCodeBatchUsageUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdate) SetNillableBatchID(v *string) *RedeemCodeBatchUsageUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeBatchUsageUpdate) SetUserID(v int64) *RedeemCodeBatchUsageUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdate) SetNillableUserID(v *int64) *RedeemCodeBatchUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RedeemCodeBatchUsageUpdate) AddUserID(v int64) *RedeemCodeBatchUsageUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeBatchUsageUpdate) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdate) SetNillableRedeemCodeID(v *int64) *RedeemCodeBatchUsageUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemCodeBatchUsageUpdate) AddRedeemCodeID(v int64) *RedeemCodeBatchUsageUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeBatchUsageUpdate) SetUsedAt(v time.Time) *RedeemCodeBatchUsageUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdate) SetNillableUsedAt(v *time.Time) *RedeemCodeBatchUsageUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// Mutation returns the RedeemCodeBatchUsageMutation object of the builder.
func (_u *RedeemCodeBatchUsageUpdate) Mutation() *RedeemCodeBatchUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCodeBatchUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeBatchUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCodeBatchUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeBatchUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeBatchUsageUpdate) check() error {
	if v, ok := _u.mutation.BatchID(); ok {
		if err := redeemcodebatchusage.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "RedeemCodeBatchUsage.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCodeBatchUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodebatchusage.Table, redeemcodebatchusage.Columns, sqlgraph.NewFieldSpec(redeemcodebatchusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(redeemcodebatchusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemcodebatchusage.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUsedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodebatchusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCodeBatchUsageUpdateOne is the builder for updating a single RedeemCodeBatchUsage entity.
type RedeemCodeBatchUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCodeBatchUsageMutation
}

// SetBatchID sets the "batch_id" field.
func (_u *RedeemCodeBatchUsageUpdateOne) SetBatchID(v string) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdateOne) SetNillableBatchID(v *string) *RedeemCodeBatchUsageUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeBatchUsageUpdateOne) SetUserID(v int64) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdateOne) SetNillableUserID(v *int64) *RedeemCodeBatchUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RedeemCodeBatchUsageUpdateOne) AddUserID(v int64) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeBatchUsageUpdateOne) SetRedeemCodeID(v int64) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdateOne) SetNillableRedeemCodeID(v *int64) *RedeemCodeBatchUsageUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemCodeBatchUsageUpdateOne) AddRedeemCodeID(v int64) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeBatchUsageUpdateOne) SetUsedAt(v time.Time) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeBatchUsageUpdateOne) SetNillableUsedAt(v *time.Time) *RedeemCodeBatchUsageUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// Mutation returns the RedeemCodeBatchUsageMutation object of the builder.
func (_u *RedeemCodeBatchUsageUpdateOne) Mutation() *RedeemCodeBatchUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the RedeemCodeBatchUsageUpdate builder.
func (_u *RedeemCodeBatchUsageUpdateOne) Where(ps ...predicate.RedeemCodeBatchUsage) *RedeemCodeBatchUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCodeBatchUsageUpdateOne) Select(field string, fields ...string) *RedeemCodeBatchUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCodeBatchUsage entity.
func (_u *RedeemCodeBatchUsageUpdateOne) Save(ctx context.Context) (*RedeemCodeBatchUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeBatchUsageUpdateOne) SaveX(ctx context.Context) *RedeemCodeBatchUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCodeBatchUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeBatchUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeBatchUsageUpdateOne) check() error {
	if v, ok := _u.mutation.BatchID(); ok {
		if err := redeemcodebatchusage.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "RedeemCodeBatchUsage.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCodeBatchUsageUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCodeBatchUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodebatchusage.Table, redeemcodebatchusage.Columns, sqlgraph.NewFieldSpec(redeemcodebatchusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCodeBatchUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcodebatchusage.FieldID)
		for _, f := range fields {
			if !redeemcodebatchusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcodebatchusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(redeemcodebatchusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcodebatchusage.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemcodebatchusage.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcodebatchusage.FieldUsedAt, field.TypeTime, value)
	}
	_node = &RedeemCodeBatchUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodebatchusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
