// Code generated by ent, DO NOT EDIT.

package redeemcodebatchusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLTE(FieldID, id))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldBatchID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldUserID, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldRedeemCodeID, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldUsedAt, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNotIn(FieldBatchID, vs...))
}

// BatchIDGT applies the GT predicate on the "batch_id" field.
func BatchIDGT(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGT(FieldBatchID, v))
}

// BatchIDGTE applies the GTE predicate on the "batch_id" field.
func BatchIDGTE(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGTE(FieldBatchID, v))
}

// BatchIDLT applies the LT predicate on the "batch_id" field.
func BatchIDLT(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLT(FieldBatchID, v))
}

// BatchIDLTE applies the LTE predicate on the "batch_id" field.
func BatchIDLTE(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLTE(FieldBatchID, v))
}

// BatchIDContains applies the Contains predicate on the "batch_id" field.
func BatchIDContains(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldContains(FieldBatchID, v))
}

// BatchIDHasPrefix applies the HasPrefix predicate on the "batch_id" field.
func BatchIDHasPrefix(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldHasPrefix(FieldBatchID, v))
}

// BatchIDHasSuffix applies the HasSuffix predicate on the "batch_id" field.
func BatchIDHasSuffix(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldHasSuffix(FieldBatchID, v))
}

// BatchIDEqualFold applies the EqualFold predicate on the "batch_id" field.
func BatchIDEqualFold(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEqualFold(FieldBatchID, v))
}

// BatchIDContainsFold applies the ContainsFold predicate on the "batch_id" field.
func BatchIDContainsFold(v string) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldContainsFold(FieldBatchID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLTE(FieldUserID, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLTE(FieldRedeemCodeID, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.FieldLTE(FieldUsedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCodeBatchUsage) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCodeBatchUsage) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCodeBatchUsage) predicate.RedeemCodeBatchUsage {
	return predicate.RedeemCodeBatchUsage(sql.NotPredicates(p))
}
